"""
配置模块
"""
from configs.constants import (
    DEFAULT_SCHEMA,
    MAX_CLARIFICATION_TURNS,
    DEFAULT_MODEL,
    FAST_MODEL,
    SMART_MODEL,
    DEFAULT_TIMEOUT,
    LONG_TIMEOUT,
    LOW_TEMP,
    MID_TEMP,
    HIGH_TEMP
)

from configs.prompts import (
    SCHEMA_GENERATION_PROMPT,
    EXTRACTION_PROMPT,
    FORCE_FILL_PROMPT,
    CLARIFICATION_PROMPT,
    PARSE_RESPONSE_PROMPT,
    MODIFICATION_PROMPT
)

__all__ = [
    "DEFAULT_SCHEMA",
    "MAX_CLARIFICATION_TURNS",
    "DEFAULT_MODEL",
    "FAST_MODEL",
    "SMART_MODEL",
    "DEFAULT_TIMEOUT",
    "LONG_TIMEOUT",
    "LOW_TEMP",
    "MID_TEMP",
    "HIGH_TEMP",
    "SCHEMA_GENERATION_PROMPT",
    "EXTRACTION_PROMPT",
    "FORCE_FILL_PROMPT",
    "CLARIFICATION_PROMPT",
    "PARSE_RESPONSE_PROMPT",
    "MODIFICATION_PROMPT"
]
